import './index.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ConditionalLayout from "@/components/ConditionalLayout";
<<<<<<< HEAD
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; 
=======
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; 

>>>>>>> 6a536cf2f05d166c40d0e51f50f7e731c6cc78b8

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={`${inter.className} relative`}>
        <ConditionalLayout>
          {children}
        </ConditionalLayout>
      <body className={inter.className}>
        <AntdRegistry>{children}</AntdRegistry>
        <ToastContainer
=======

      <body className={`${inter.className} relative`}>
        <ConditionalLayout>
          {children}
           <ToastContainer
>>>>>>> 6a536cf2f05d166c40d0e51f50f7e731c6cc78b8
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
<<<<<<< HEAD
=======
        </ConditionalLayout>
       

>>>>>>> 6a536cf2f05d166c40d0e51f50f7e731c6cc78b8
      </body>
    </html>
  );
}
