import "./index.css";

import type { Metadata } from "next";

import { Toaster } from "@/components/ui/toaster";

import { TaskstacktProvider } from "./providers/queryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TaskstacktProvider>
          {children}
          <Toaster />
        </TaskstacktProvider>
      </body>
    </html>
  );
}
